noddys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include("website.urls", namespace="website")),
    url(r'^photologue/', include('photologue.urls', namespace='photologue')),
    url(r'^admin/', admin.site.urls),
]

website/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^about/$', views.about, name="about"),
    url(r'^classes/$', views.classes, name="classes"),
    url(r'^management/$', views.management, name="management"),
]

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

class HomepageSlider(models.Model):
    date_added = models.DateField(default=timezone.now)
    title = models.CharField(max_length=100)
    image = models.FileField(max_length=150, upload_to="homepage-slider")
    content = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Query(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=150)
    mobile = models.BigIntegerField(blank=True, null=True)
    message = models.TextField(blank=True, null=True)

    def __str__(self):
        return "Query by " + self.name

class Testimonial(models.Model):
    date_added = models.DateTimeField(default=timezone.now)
    parent_name = models.CharField(max_length=150)
    child_name = models.CharField(max_length=150)
    parent_title = models.CharField(max_length=150)
    parent_image = models.FileField(upload_to="testimonials", blank=True, null=True, max_length=150)
    testimonial = models.TextField()

    def __str__(self):
        return self.parent_name

website/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Testimonial

def index(request):
    testimonials = Testimonial.objects.filter()[:5]

    return render(request, "index-2.html", {
    "test":testimonials,
    })

def contact(request):
    return render(request, "contact.html", {})

def about(request):
    return render(request, "about.html", {})

def classes(request):
    return render(request, "classes.html", {})

def management(request):
    return render(request, "teachers.html", {})

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}{% endblock title %} | Best Play School in Delhi | Jyoti's Noddy Play School</title>
    <link href="images/favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon"/>
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Font-awesome -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Flaticon -->
    <link href="{% static "assets/flaticon/flaticon.css" %}" rel="stylesheet">

    <!-- lightcase -->
    <link href="{% static "assets/css/lightcase.css" %}" rel="stylesheet">

    <!-- Swiper -->
    <link href="{% static "assets/css/swiper.min.css" %}" rel="stylesheet">

    <!-- quick-view -->
    <link href="{% static "assets/css/quick-view.css" %}" rel="stylesheet">

    <!-- nstSlider -->
    <link href="{% static "assets/css/jquery.nstSlider.css" %}" rel="stylesheet">

    <!-- flexslider -->
    <link href="{% static "assets/css/flexslider.css" %}" rel="stylesheet">

    <!-- Style -->
    <link href="{% static "assets/css/style.css" %}" rel="stylesheet">

    <!-- Responsive -->
    <link href="{% static "assets/css/responsive.css" %}" rel="stylesheet">


  </head>

  <body>

    {% include "header.html" %}
    {% block content %}
    {% endblock content %}
    {% include "footer.html" %}

    <!-- jquery -->
    <script src="{% static "assets/js/jquery-1.12.4.min.js" %}"></script>

    <!-- Bootstrap -->
    <script src="{% static "assets/js/bootstrap.min.js" %}"></script>

    <!-- Isotope -->
    <script src="{% static "assets/js/isotope.min.js" %}"></script>

    <!-- lightcase -->
    <script src="{% static "assets/js/lightcase.js" %}"></script>

    <!-- counterup -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="{% static "assets/js/jquery.counterup.min.js" %}"></script>

    <!-- Swiper -->
    <script src="{% static "assets/js/swiper.jquery.min.js" %}"></script>

    <!--progress-->
    <script src="{% static "assets/js/circle-progress.min.js" %}"></script>

    <!--velocity-->
    <script src="{% static "assets/js/velocity.min.js" %}"></script>

    <!--quick-view-->
    <script src="{% static "assets/js/quick-view.js" %}"></script>

    <!--nstSlider-->
    <script src="{% static "assets/js/jquery.nstSlider.js" %}"></script>

    <!--flexslider-->
    <script src="{% static "assets/js/flexslider-min.js" %}"></script>

    <!--easing-->
    <script src="{% static "assets/js/jquery.easing.min.js" %}"></script>

    <!-- custom -->
    <script src="{% static "assets/js/custom.js" %}"></script>

  </body>
  </html>

templates/footer.html
<!-- Subscribe Start here -->
<section class="subscribe subscribe-two">
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-12 col-xs-12">
        <h3>Join Our Newsletter</h3>
      </div>
      <div class="col-md-7 col-sm-12 col-xs-12">
        <form action="http://demos.codexcoder.com/">
          <input type="text" placeholder="Enter your e-mail here">
          <input type="submit" value="Subscribe Now">
        </form>
      </div>
    </div><!-- row -->
  </div><!-- container -->
</section><!-- subscribe -->
<!-- Subscribe End here -->

<!-- Footer Start here -->
<footer>
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
          <p>&copy; 2017. Jyoti's Noddy Play School. Designed By <a href="https://www.delhinerds.com" target="_blank">Delhi Nerds</a></p>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
          <ul class="social-default">
            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
          </ul>
        </div>
      </div><!-- row -->
    </div><!-- container -->
  </div><!-- footer bottom -->
</footer>
<!-- Footer End here -->

templates/header.html
{% load staticfiles %}

<header class="header-two">
  <div class="header-top">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <a class="logo" href="{% url "website:index" %}"><img src="{% static "images/logo.png" %}" alt="logo" class="img-responsive"></a>
        </div>
        <div class="col-md-9" style="padding-top:30px;">
          <ul class="top-contents">
            <li>
              <i class="icon flaticon-phone-call"></i>
              <div class="content">
                <p>Call Us Anytime</p>
                <span>+91-9899266339</span>
              </div>
            </li>
            <li>
              <i class="icon flaticon-alarm-clock"></i>
              <div class="content">
                <p>Opening Time</p>
                <span>9:15am-12:30pm</span>
              </div>
            </li>
            <li>
              <i class="icon flaticon-signs"></i>
              <div class="content">
                <p>Our Address</p>
                <span>F-100, Kirti Nagar, Delhi</span>
              </div>
            </li>
          </ul>
        </div>
      </div><!-- row -->
    </div><!-- container -->
  </div><!-- header top -->
    <div class="main-menu">
      <nav class="navbar ">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html"><img src="{% static "images/logo.png" %}" alt="logo" class="img-responsive"></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><a href="{% url "website:index" %}">Home</a></li>
              <li><a href="{% url "website:about" %}">About Us</a></li>
              <li><a href="{% url "website:classes" %}">Classes</a></li>
              <li><a href="/pages/programs/">Our Programs</a></li>
              <li><a href="{% url "website:index" %}">Gallery</a></li>
              <li><a href="{% url "website:management" %}">Management</a></li>
              <li><a href="{% url "website:contact" %}">Contact Us</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><span class="menu-search"><i class="fa fa-search" aria-hidden="true"></i></span></li>
              <li class="menu-button"><a href="#" class="button-default">Admissions</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
  </div><!-- main menu -->
</header>
<!-- header End here -->

templates/index-2.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Home{% endblock title %}

{% block content %}

    <!-- Banner Start here -->
    <section class="banner banner-two">
      <div class="banner-slider swiper-container">
        <div class="swiper-wrapper">
          <div class="banner-item slide-one swiper-slide">
            <div class="banner-overlay"></div>
              <div class="container">
                <div class="banner-content">
                  <h3>Welcome to Jyoti's Noddy Place School</h3>
                  <h2>A Home Away from Home</h2>
                  <p>One of the most far-reaching decisions parents can make is the choice of a play school for their children. Now finding the right one is no more difficult.
                  </p>
                </div><!-- banner-content -->
              </div><!-- container -->
          </div><!-- slide item -->
          <div class="banner-item slide-two swiper-slide">
            <div class="banner-overlay"></div>
              <div class="container">
                <div class="banner-content">
                  <h3>After School Awareness Program (ASAP)</h3>
                  <h2>The future leader's programs</h2>
                  <p>Under ASAP we conduct “The Future Leaders Program” which gives students the chance to learn and develop leadership skills together.</p>
                </div><!-- banner-content -->
              </div><!-- container -->
          </div><!-- slide item -->

        </div><!-- swiper-wrapper -->
        <div class="swiper-pagination"></div>
      </div><!-- swiper-container -->
    </section><!-- banner -->
    <!-- Banner End here -->


  	<!-- facility Start here -->
  	<section class="facility facility-two">
  		<div class="container">
				<div class="facility-items">
          <div class="facility-item">
            <div class="front-part">
              <span class="icon-two flaticon-symbols"></span>
              <h4>Active Learning</h4>
            </div>
            <div class="back-part">
              <span class="icon-two flaticon-symbols"></span>
              <h4>Active Learning</h4>
              <p>Distinctively enhance empowered and alignments without leveraged architectures professionly.</p>
            </div>
          </div><!-- facility item -->
          <div class="facility-item">
            <div class="front-part">
              <span class="icon-two flaticon-avatar"></span>
              <h4>Expert Teachers</h4>
            </div>
            <div class="back-part">
              <span class="icon-two flaticon-avatar"></span>
              <h4>Expert Teachers</h4>
              <p>Distinctively enhance empowered and alignments without leveraged architectures professionly.</p>
            </div>
          </div><!-- facility item -->
          <div class="facility-item">
            <div class="front-part">
              <span class="icon-two flaticon-world"></span>
              <h4>Convenient Location</h4>
            </div>
            <div class="back-part">
              <span class="icon-two flaticon-world"></span>
              <h4>Strategi Location</h4>
              <p>Distinctively enhance empowered and alignments without leveraged architectures professionly.</p>
            </div>
          </div><!-- facility item -->
          <div class="facility-item">
            <div class="front-part">
              <span class="icon-two flaticon-line-chart"></span>
              <h4>Day Care</h4>
            </div>
            <div class="back-part">
              <span class="icon-two flaticon-line-chart"></span>
              <h4>Full Day Programs</h4>
              <p>Distinctively enhance empowered and alignments without leveraged architectures professionly</p>
            </div>
          </div><!-- facility item -->
        </div><!-- facility items -->
  		</div><!-- container -->
  	</section><!-- facility -->
  	<!-- facility End here -->


  	<!-- About Start here -->
  	<section class="about about-two padding-120">
  		<div class="container">
  			<div class="row">
  				<div class="col-md-6">
  					<div class="about-image">
  						<img src="{% static "images/about/about-2.png" %}" alt="about image" class="img-responsive">
  					</div>
  				</div>
  				<div class="col-md-6">
  					<div class="about-content">
  						<h3>Welcome to Jyoti's Noddy Play School</h3>
  						<p>
                One of the most far-reaching decisions parents can make is the choice of a play school for their children. Now finding the right one is no more difficult.<br /><br />
                Jyoti’s Noddy Play School (formerly known as Noddys Play School) was established in 1989.<br /><br />
                The environment at Jyoti’s Noddy Play School is designed to make kids feel at home and continue to help them develop into responsible young adults.
              </p>
  					</div><!-- about content -->
  				</div>
  			</div><!-- row -->
  		</div><!-- container -->
  	</section><!-- about -->
  	<!-- About End here -->

    <!-- Features Start here -->
    <section class="features padding-120">
      <div class="container">
        <div class="section-header">
          <h3>Why Choose Noddy's Play School</h3>
          <p>Rapidiously expedite granular imperatives before economically sound web services. Credibly actualize pandemic strategic themeplatform.</p>
        </div>
        <div class="row">
          <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="features-left">
              <div class="feature-item">
                <div class="icon flaticon-people-1"></div>
                <div class="content">
                  <h4>The Environment</h4>
                    <p>The environment at Jyoti’s Noddy Play School is designed to make kids feel at home and continue to help them develop into responsible young adults.
                  </p>
                </div>
              </div><!-- feature item -->
              <div class="feature-item">
                <div class="icon flaticon-symbols"></div>
                <div class="content">
                  <h4>Small Classes</h4>
                  <p>Classes are small and the staff carefully selected. There is a feeling of family and a rich and fertile atmosphere for ideas and creativity to grow.</p>
                </div>
              </div><!-- feature item -->
              <div class="feature-item">
                <div class="icon flaticon-microphone"></div>
                <div class="content">
                  <h4>Music And Art Class</h4>
                  <p>Our program not only prepares its young graduates to face the challenge of the future, but also instils within them such essential qualities as self-reliance, self-discipline, leadership and social grace.
                  </p>
                </div>
              </div><!-- feature item -->
            </div><!-- feature left -->
          </div>
          <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="feature-image">
              <img src="{% static "images/feature.jpg" %}" alt="feature image" class="img-responsive">
            </div>
          </div>
          <div class="col-md-4 col-sm-12 col-xs-12">
            <div class="features-right">
              <div class="feature-item">
                <div class="icon flaticon-home"></div>
                <div class="content">
                  <h4>Play, Grow, Lear and Smile</h4>
                  <p>Each day we provide a selection of structured and unstructured activities, offering children plenty of choice.</p>
                </div>
              </div><!-- feature item -->
              <div class="feature-item">
                <div class="icon flaticon-line-chart"></div>
                <div class="content">
                  <h4>Safety</h4>
                  <p>Jyoti’s Noddy Play School provides a safe, nurturing and developmentally appropriate program which fosters active learning in a child friendly environment.
                  </p>
                </div>
              </div><!-- feature item -->
              <div class="feature-item">
                <div class="icon flaticon-signs"></div>
                <div class="content">
                  <h4>Our Vision</h4>
                  <p>Our vision is to be recognized as outstanding childcare programs, creating societies next generation of leaders through play, exploration and coaching.
                  </p>
                </div>
              </div><!-- feature item -->
            </div><!-- feature left -->
          </div>
        </div><!-- row -->
      </div><!-- container -->
    </section><!-- features -->
  	<!-- Features End here -->


  	<!-- Gallery Start here -->
  	<section class="gallery gallery-two">
  		<div class="overlay padding-120">
  			<div class="section-header bg">
          <h3>Our School Gallery</h3>
          <p>Rapidiously expedite granular imperatives before economically sound web services. Credibly actualize pandemic strategic themeplatform.</p>
        </div>

          <div class="gallery-two-items">
            <div class="gallery-item">
              <div class="gallery-image">
                <img src="images/gallery/gallery_07.jpg" alt="gallery image" class="img-responsive">
                <div class="gallery-overlay"><div class="bg"></div></div>
                <div class="gallery-content">
                  <a href="images/gallery/gallery_bg_01.jpg" data-rel="lightcase:myCollection"><i class="icon flaticon-expand"></i></a>
                  <h4>Product Name Here</h4>
                  <span>By: KidsAcademy Theme</span>
                </div>
              </div>
            </div><!-- gallery item -->
            <div class="gallery-item">
              <div class="gallery-image">
                <img src="images/gallery/gallery_08.jpg" alt="gallery image" class="img-responsive">
                <div class="gallery-overlay"><div class="bg"></div></div>
                <div class="gallery-content">
                  <a href="images/gallery/gallery_bg_01.jpg" data-rel="lightcase:myCollection"><i class="icon flaticon-expand"></i></a>
                  <h4>Product Name Here</h4>
                  <span>By: KidsAcademy Theme</span>
                </div>
              </div>
            </div><!-- gallery item -->
            <div class="gallery-item">
              <div class="gallery-image">
                <img src="images/gallery/gallery_09.jpg" alt="gallery image" class="img-responsive">
                <div class="gallery-overlay"><div class="bg"></div></div>
                <div class="gallery-content">
                  <a href="images/gallery/gallery_bg_01.jpg" data-rel="lightcase:myCollection"><i class="icon flaticon-expand"></i></a>
                  <h4>Product Name Here</h4>
                  <span>By: KidsAcademy Theme</span>
                </div>
              </div>
            </div><!-- gallery item -->
            <div class="gallery-item">
              <div class="gallery-image">
                <img src="images/gallery/gallery_10.jpg" alt="gallery image" class="img-responsive">
                <div class="gallery-overlay"><div class="bg"></div></div>
                <div class="gallery-content">
                  <a href="images/gallery/gallery_bg_01.jpg" data-rel="lightcase:myCollection"><i class="icon flaticon-expand"></i></a>
                  <h4>Product Name Here</h4>
                  <span>By: KidsAcademy Theme</span>
                </div>
              </div>
            </div><!-- gallery item -->
          </div><!-- gallery items -->
          <div class="gallery-button"><a href="gallery.html" class="button-default">View More Gallery</a></div>
  		</div><!-- overlay -->
  	</section><!-- gallery -->
  	<!-- Gallery End here -->


  	{% include "testimonial.html" %}


{% endblock content %}

templates/testimonial.html
<!-- Testimonial Start here -->
<section class="testimonial padding-120">
  <div class="container">
    <div class="section-header">
    <h3>What Parents Say</h3>
  </div>
  <div class="testimonial-items">
    <div class="testimonial-slider swiper-container">
      <div class="swiper-wrapper">
        {% for each in test %}
          <div class="testimonial-item swiper-slide">
            <div class="testimonial-details">
              <p>{{each.testimonial|safe}}</p>
              <h4>{{each.parent_name}}<span>{{each.parent_title}}</span></h4>
              <img src="images/testimonial/testimonial_icon_01.jpg" alt="testimonial icon" class="img-responsive">
            </div>
            <div class="testimonial-image">
              <img src="{{each.parent_image.url}}" alt="client image" class="img-responsive">
            </div>
          </div><!-- testimonial-item -->
        {% endfor %}
      </div><!-- swiper-wrapper -->
    </div><!-- swiper-container -->
      </div><!-- testimonial-items -->
  </div><!-- container -->
</section><!-- testimonial -->
<!-- Testimonial End here -->